name: remote_mouse_server
description: Remote Mouse Flutter application with modern Android client
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Platform specific
  win32: ^5.14.0
  
  # UI & Design
  qr_flutter: ^4.1.0
  material_color_utilities: ^0.8.0
  
  # State Management & Architecture
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Network & Communication
  web_socket_channel: ^2.4.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Storage & Caching
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Utils
  clipboard: ^0.1.3
  window_manager: ^0.4.2
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Logging & Debugging
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.2
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
